[package]
name = "cipher_browser"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
aes = "0.7.5"
block-modes = "0.8.1"
base64 = "0.13.0"
sha2 = "0.9.8"
getrandom = { version = "0.2", features = ["js"] }
